language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
 - true
install:
 - "sudo apt-get update"
 - "sudo apt-get install lib32stdc++6 lib32z1"
before_script:
 - "chmod +x gradlew"
script:
 - "./gradlew travis"
after_success:
 - true
after_failure:
 - true
after_script:
 - true